export default {
    SUCCESS: 'The opration has been successful',
    ERROR: 'The opration has an error',
    NOT_FOUND: (entity) => `${entity} not found`,
    TOO_MANY_REQUEST: 'Too many request please try again later',
    ALREADY_EXIST: (entity, value) => `${entity} already exist with ${value}`,
    INVALID_ACCOUNT_CONFIRMATION_TOKEN_OR_CODE: 'Invalid account confirmation token or code',
    ACCOUNT_ALREADY_CONFIRMED: 'Account already confirmed',
    INVALID_CREDENTIALS: 'Invalid E-mail or Password, Please try again.',
    UNAUTHORIZED: 'Unauthorized, please login first',
    ACCOUNT_CONFIRMATION_REQUIRED: 'Account confirmation required',
    PASSWORD_RESET_URL_EXPIRED: 'Password reset url expired',
    INVALID_REQUEST: 'Invalid request',
    INVALID_OLD_PASSWORD: 'Invalid old password',
    PASSWORD_MATCHING_WITH_OLD_PASSWORD: 'Password matching with old password',
    INVALID_ACCOUNT_TYPE: 'Invalid account type',
    CASH_ACCOUNT_FOUND: 'Only single cash account allowed',
    CATEGORY_FOUND: 'Category already exist',
    Limit_CATEGORY_10: 'You can not add more than 10 category',
}
